
 # Name of the pipeline
name: Java CI with Maven   

# Pipeline will trigger when code is committed to Main branch / When pull request made to main branch then pipeline will trigger.
on:
  push:
    branches: [ "Main" ]     
  pull_request:
    branches: [ "Main" ]


# Github jobs 
jobs:
  # the build job
  build:

    # This job will be run on ubuntu machine runner
    runs-on: ubuntu-latest

    steps:

    - name: code check out 
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run:  mvn clean install package --file pom.xml

     - name: Docker build
      run: |
        docker build . 
